### ISSUE TITLE
Cant get app to start

### ISSUE THREAD

**Issue by gitblah** [codersForFun/react-keystone-boilerplate#5]
I have followed the install steps with the latest version that corrects the issue with react,15.4 (although there is still a peer dependency issue with react-addons-shallow-compare@15.4.1) 

Webpack seems to run ok but nothing happens, I cant access the app. I am not sure what I am supposed to see as there is no error message etc.

This is the output of npm run start... any ideas what I am doing wrong or what I should be seeing or how to debug?

Also the instructions point to the old repo... probably needs an update :)

```
`$ npm run start

> generic-name@0.0.1 start D:\Development\KeystoneReact5\react-keystone-boilerplate
> npm run watch&npm run keystone


> generic-name@0.0.1 watch D:\Development\KeystoneReact5\react-keystone-boilerplate
> webpack --watch

Hash: 8791915e899d14f135f2
Version: webpack 1.13.2
Time: 4218ms
                      Asset       Size  Chunks             Chunk Names
      ../images/reactjs.png    12.9 kB          [emitted]
                  bundle.js    1.33 MB       0  [emitted]  main
    f888990ca66154a228cd.js    2.12 kB       1  [emitted]
    24883879fd9d7d182ed9.js  903 bytes       2  [emitted]
        ../styles/style.css    11.7 kB       0  [emitted]  main
              bundle.js.map    1.59 MB       0  [emitted]  main
    ../styles/style.css.map   96 bytes       0  [emitted]  main
f888990ca66154a228cd.js.map     1.7 kB       1  [emitted]
24883879fd9d7d182ed9.js.map  818 bytes       2  [emitted]
    + 668 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
                    Asset     Size  Chunks             Chunk Names
    ../images/reactjs.png  12.9 kB          [emitted]
        + 3 hidden modules
`
```

**Comment by ames89** [comment]
Hi!

Yup, those comments are from webpack building the bundle, but next in the logs there should be 3 lines with the next information

```
------------------------------------------------
KeystoneJS Started:
React App Keystone is ready on port 3000
------------------------------------------------
```

with that information, the keystone shoutld tell you that you can access your new website in that port

if it doesn't work, please tell us

greetings!

--EDIT
i forgot to tell you, you should have running mongo on its default port: 27017

**Comment by gitblah** [comment]
That's what I was expecting except that wepback (or something else) appears to be failing silently. The "ready on port"never displays, the console just seems to hang forever right after " + 3 hidden modules".

I am on windows so maybe that has something to do with it but I was hoping there would be some kind of log or error message to help track down why it doesn't work.

I have mongo as a service so that is not an issue. I have also managed to get the original keystone react working repo working as well as a bunch of others. The difference with this repo seems to be the latest react version which appears flaky as hell given all the dependency issues it generated.

I guess if its all working straight from the repo for everyone else it is something specific to me (I am still getting a peer dependency issue after the downgraded react version and I think webpack has issues with paths in windows so maybe that is it). 

All good, I think bootstrap might just be safer for my experience level :)

**Comment by gitblah** [comment]
If anyone else experiences this issue it can be resolved by turning off the hot reloading 
i.e. removing the --watch config value from package.json
